### ISSUE TITLE
Help section Version and License links are broken

### ISSUE THREAD

**Issue by tarcisio-marinho** [mkermani144/wanna#244] opened 2017-11-18 17:14 UTC
When clicking on the Version of Flex alpha and License, redirects to the github broken link:
[https://github.com/mkermani144/wanna/releases/tag/flex-alpha](url)
[https://github.com/mkermani144/wanna/blob/master/LICENSE.md](url)

Also would be great to have a manual on the help section. 
such as: [https://github.com/mkermani144/wanna#philosophy](url)
and workflow: [https://github.com/mkermani144/wanna#workflow](url)

**Comment by mkermani144** [comment] 2017-11-19 06:34
@tarcisio-marinho 
Thanks for the bug report. It will be fixed in the next version of Wanna. PRs are also welcomed if you favor to fix the bug yourself.

**Comment by mkermani144** [comment] 2017-12-03 18:46
This first part of the issue is fixed via #250. A manual (probably containing philosophy and workflow) will be added to the help section in the future when an acceptable help is implemented for the app, but as I don't know when this help will be available, I close this issue and postpone the second part of this issue to the future.

**Closed by mkermani144** 2017-12-03 18:46 UTC
Labels: bug, help wanted, important
